# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_postmark_utils', '0002_auto_20180124_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pickled_obj',
            field=models.BinaryField(help_text='Pickled message object', verbose_name='Pickled object'),
        ),
    ]
