# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_postmark_utils', '0003_auto_20180124_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounce',
            name='has_been_delivered',
            field=models.BooleanField(default=False, help_text='If the message has been delivered, after the bounce happened', verbose_name='Has been delivered'),
        ),
    ]
