# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_postmark_utils', '0004_bounce_has_been_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_been_resent',
            field=models.BooleanField(default=False, help_text='If the message has been resent, after an exception prevented this from happening the first time round', verbose_name='Has been resent'),
        ),
    ]
