# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_postmark_utils', '0005_message_has_been_resent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resend', models.BooleanField(default=False, help_text='If the email is a resend of a previous one', verbose_name='Is resend')),
                ('msg_id', models.CharField(help_text="The 'Message-ID' header field of the email", max_length=255, unique=True, verbose_name='Message ID')),
                ('date', models.DateTimeField(help_text="The 'Date' header field of the email", verbose_name='Date')),
                ('subject', models.CharField(blank=True, help_text="The 'Subject' header field of the email", max_length=255, verbose_name='Subject')),
                ('from_email', models.CharField(blank=True, help_text="The 'From' header field of the email", max_length=255, verbose_name='Sender email address')),
                ('to_emails', models.TextField(blank=True, help_text="The 'To' field of the email, with email addresses separated by commas", verbose_name='Recipient email addresses')),
                ('cc_emails', models.TextField(blank=True, help_text="The 'Cc' field of the email, with email addresses separated by commas", verbose_name="Cc'd recipient email addresses")),
                ('bcc_emails', models.TextField(blank=True, help_text="The 'Bcc' field of the email, with email addresses separated by commas", verbose_name="Bcc'd recipient email addresses")),
                ('sending_error', models.TextField(blank=True, help_text='String version of the exception encountered while trying to send the email', verbose_name='Sending error')),
                ('delivery_submission_date', models.DateTimeField(blank=True, help_text='When the email was submitted for delivery', null=True, verbose_name='Delivery-submission date')),
                ('delivery_msg_id', models.CharField(blank=True, help_text="The 'Message-ID' header field of the email, as set by Postmark", max_length=255, null=True, unique=True, verbose_name='Delivery message ID')),
                ('delivery_error_code', models.IntegerField(blank=True, help_text="The delivery error code of the email, as specified <a target='_blank' href='https://postmarkapp.com/developer/api/overview#error-codes'>here</a>", null=True, verbose_name='Delivery error code')),
                ('delivery_message', models.CharField(blank=True, help_text='The response message from Postmark', max_length=255, verbose_name='Delivery message')),
            ],
            options={
                'verbose_name': 'email',
                'ordering': ['-date'],
                'verbose_name_plural': 'emails',
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.RemoveField(
            model_name='bounce',
            name='has_been_delivered',
        ),
        migrations.RemoveField(
            model_name='bounce',
            name='has_been_resent',
        ),
        migrations.RemoveField(
            model_name='bounce',
            name='message',
        ),
        migrations.RemoveField(
            model_name='bounce',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='message',
            name='bcc_emails',
        ),
        migrations.RemoveField(
            model_name='message',
            name='cc_emails',
        ),
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='delivery_error_code',
        ),
        migrations.RemoveField(
            model_name='message',
            name='delivery_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='delivery_message_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='delivery_submission_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='message',
            name='has_been_resent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='pickled_obj',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_emails',
        ),
        migrations.AddField(
            model_name='bounce',
            name='email_address',
            field=models.TextField(default='', help_text='The email address the bounce is for', verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='email_address',
            field=models.TextField(default='', help_text='The email address the delivery is to', verbose_name='Email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_obj',
            field=models.BinaryField(default=b'', help_text='Serialisation of the originally-sent "email.message.Message" (or a subclass) object, in pickle format', verbose_name='Message object'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='resend_for_id',
            field=models.CharField(default='', help_text='ID used internally by the app, to match an email to the message it has been resent for, by being sent in the email header', max_length=255, unique=True, verbose_name='Resend for ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bounce',
            name='email',
            field=models.ForeignKey(help_text='The email the bounce is for', on_delete=django.db.models.deletion.CASCADE, related_name='bounces', to='django_postmark_utils.Email', verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bounce',
            name='type_code',
            field=models.IntegerField(help_text="The type code of the bounce, as specified <a target='_blank' href='https://postmarkapp.com/developer/api/bounce-api#bounce-types'>here</a>", verbose_name='Type code'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='email',
            field=models.ForeignKey(help_text='The email the delivery is for', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='django_postmark_utils.Email', verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='email',
            name='message',
            field=models.ForeignKey(help_text='The message the email is for', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='django_postmark_utils.Message', verbose_name='Message'),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='raw_data',
        ),
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together=set([('email', 'email_address')]),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='message',
        ),
    ]
