# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_postmark_utils', '0006_auto_20180130_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='bcc_emails',
        ),
        migrations.RemoveField(
            model_name='email',
            name='cc_emails',
        ),
        migrations.RemoveField(
            model_name='email',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='email',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='email',
            name='to_emails',
        ),
        migrations.AddField(
            model_name='message',
            name='bcc_emails',
            field=models.TextField(blank=True, help_text="The 'Bcc' field of the email, with email addresses separated by commas", verbose_name="Bcc'd recipient email addresses"),
        ),
        migrations.AddField(
            model_name='message',
            name='cc_emails',
            field=models.TextField(blank=True, help_text="The 'Cc' field of the email, with email addresses separated by commas", verbose_name="Cc'd recipient email addresses"),
        ),
        migrations.AddField(
            model_name='message',
            name='from_email',
            field=models.CharField(blank=True, help_text="The 'From' header field of the email", max_length=255, verbose_name='Sender email address'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, help_text="The 'Subject' header field of the email", max_length=255, verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_emails',
            field=models.TextField(blank=True, help_text="The 'To' field of the email, with email addresses separated by commas", verbose_name='Recipient email addresses'),
        ),
    ]
