# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_postmark_utils', '0007_auto_20180131_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='delivery_msg_id',
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_resend',
        ),
        migrations.RemoveField(
            model_name='email',
            name='msg_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='resend_for_id',
        ),
        migrations.AddField(
            model_name='email',
            name='delivery_email_id',
            field=models.CharField(blank=True, help_text="The 'Message-ID' header field of the email, as set by Postmark", max_length=255, null=True, unique=True, verbose_name='Delivery email ID'),
        ),
        migrations.AddField(
            model_name='email',
            name='email_id',
            field=models.CharField(default='', help_text="The 'Message-ID' header field of the email", max_length=255, unique=True, verbose_name='Email ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='', help_text='ID used internally by the app, to match an email to the message it has been resent for, by being sent in the email header', max_length=255, unique=True, verbose_name='Message ID'),
            preserve_default=False,
        ),
    ]
