sudo: false


language: python


branches:
  only:
  - master


matrix:
  fast_finish: true
  include:
    - python: 3.5
      env: TOXENV=py35-django111
    - python: 3.5
      env: TOXENV=py35-django20
    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.6
      env: TOXENV=py36-django20


before_cache:
  - rm -rf $HOME/.cache/pip/log


cache:
  directories:
    - $HOME/.cache/pip


install:
  - pip install tox


script:
  - tox
